name: Building App

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          if [ -d ".next" ]; then
            echo "Build directory exists"
          else
            echo "Build directory does not exist"
            exit 1
          fi
